### ISSUE TITLE
Dates column not showing

### ISSUE THREAD

**Issue by scholarazwa** [TablePlus/TableTool-issue-tracker#5] opened 2024-07-03 03:05 UTC
Hi,
I have a CSV file with a date column. When I open it with TableTool, the cells are all empty. But when I open with Easy CSV Editor, the dates are showing. Can you help check if this is a bug? Thank you.

TableTool:
![Screenshot 2024-07-03 at 11 01 04 AM](https://github.com/TablePlus/TableTool-issue-tracker/assets/10784481/afb2e23d-1b14-4c6a-9979-e467172fd6ef)

Easy CSV Editor:
![Screenshot 2024-07-03 at 11 01 23 AM](https://github.com/TablePlus/TableTool-issue-tracker/assets/10784481/4933ecfb-a475-468b-b21a-e11644bd4132)

**Comment by huyphams** [comment] 2024-07-03 20:00
Hi @scholarazwa I think the problem is the date-format, let me see if we can add the custom pattern for date format.

**Comment by linroex** [comment] 2024-10-08 23:44
I have same issue, my date format is: "2024-01-01" and can't show also

**Comment by huyphams** [comment] 2024-10-15 12:16
It's fixed in the build 1.2.0 Thanks!

**Closed as completed by huyphams** 2024-10-15 12:16 UTC
